version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - |
        COUNT=$(aws s3 ls s3://${RESOURCES_BUCKET}/artifacts/hail-python.zip | wc -l)
        if [ $COUNT = 1 ]; then
            echo 'skipping Hail build, already there'
        else
          echo 'Installing pre-reqs'
          yum install -y g++ cmake git
          yum install -y lz4
          yum install -y lz4-devel
          git clone $HAIL_REPO
          cd hail/hail && git checkout 0.2.93
          make install HAIL_COMPILE_NATIVES=1 SCALA_VERSION=2.12.13 SPARK_VERSION=3.1.1
          cd build
          aws s3 cp deploy/dist/hail-0.2.93-py3-none-any.whl s3://${RESOURCES_BUCKET}/artifacts/
          aws s3 cp libs/hail-all-spark.jar s3://${RESOURCES_BUCKET}/artifacts/
        fi
