version: 0.2
phases:
  install:
    runtime-versions:
          python: 3.8
    commands:
      - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      - apt-get update -y
  build:
    commands:
      - aws s3 sync ./resources s3://${RESOURCES_BUCKET} --size-only
artifacts:
  files:
    - quicksight_cfn.yml
