version: 0.2
phases:
  install:
    runtime-versions:
          python: 3.8
    commands:
      - apt-get update -y
  build:
    commands:
      - aws s3 sync ./resources s3://${RESOURCES_BUCKET} --size-only
artifacts:
  files:
    - quicksight_cfn.yml
